version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file:
      - app/db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./app/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
